---
# Config Map

apiVersion: v1
kind: ConfigMap
metadata:
  name: data-store-env
data:
  folder: "story"

---
# Defined Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
# Define Persistent Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---


# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app-container
          image: syndicate47/synimage:stories-app-1.0.0
          imagePullPolicy: Always
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: story-service
  # Additional Stuff for MicroK8 Starts
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
  # Additional Stuff for MicroK8 Ends
spec:
  selector:
    app: story-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---

