# User App Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app-container
          image: syndicate47/synimage:user-api-1.0.0
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: auth_app_address

---
# User App Service

apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# User Auth App Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth-container
          image: syndicate47/synimage:user-auth-1.0.0

---
# User Auth App Service

apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: user-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# User Task Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-task
  template:
    metadata:
      labels:
        app: user-task
    spec:
      containers:
        - name: user-task-container
          image: syndicate47/synimage:user-task-1.0.0
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: auth_app_address
            - name: TASKS_FOLDER
              value: tasks
          volumeMounts:
            - mountPath: /app/tasks
              name: tasks-volume
      volumes:
        - name: tasks-volume
          emptyDir: {}

---
# User Task Service

apiVersion: v1
kind: Service
metadata:
  name: user-task-service
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: user-task
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
# Frontend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: syndicate47/synimage:user-frontend-1.0.0
          imagePullPolicy: Always

---
# Frontend Service

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: data-store-env
data:
  auth_app_address: user-auth-service.default
